name: Auxiliary checks

on:
  workflow_run:
    workflows: ["Pull request test"]
    types:
      - requested

jobs:
  job1:
    name:  first job
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2

    - name: Get ufs-weather-model sha's
      run: |
        app="Accept: application/vnd.github.v3+json"
        url="https://api.github.com/repos/ufs-community/ufs-weather-model/branches/develop"
        sha=$(curl -sS -H "$app" $url | ./json_helper.py repository)
        echo "develop=$sha" >> GITHUB_ENV
        names="FV3 MOM6-interface/MOM6 CICE-interface/CICE WW3 stochastic_physics FMS NEMS CMEPS-interface/CMEPS DATM CMakeModules"
        for name in $names; do
          url="https://api.github.com/repos/ufs-community/ufs-weather-model/contents/$name"
          sha=$(curl -sS -H "$app" $url | ./json_helper.py component)
          echo $sha
          echo "$name=$sha"
          echo "$name=$sha" >> $GITHUB_ENV
        done
        echo $FV3
        echo "${{ env.FV3 }}"
        echo "${{ env.DATM }}"
        ./test3.sh

#    - name: try check run
#      run: |
#        head_sha=$(cat ${GITHUB_EVENT_PATH} | ./json_helper.py check_run)
#        echo $head_sha
#        echo "============================="
#        cat ${GITHUB_EVENT_PATH}
#        echo "============================="
#        comment_body="$(./repo-check.sh MinsukJi-NOAA feature/ci-regional-model)"
#        echo ${comment_body}
#        curl -sS -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" \
#        https://api.github.com/repos/MinsukJi-NOAA/check-uptodate/issues/2/comments \
#        -d '{"body": "'"${comment_body}"'"}'
