name: Auxiliary checks

on:
  workflow_run:
    workflows: ["Pull request test"]
    types:
      - requested

jobs:
  job1:
    name:  first job
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2

    - name: try check run
      run: |
        head_sha=$(cat ${GITHUB_EVENT_PATH} | ./json_helper.py check_run)
        echo $head_sha
        echo "============================="
        cat ${GITHUB_EVENT_PATH}
        echo "============================="
        comment_body="$(./repo-check.sh MinsukJi-NOAA feature/ci-regional-model)"
        echo ${comment_body}
        curl -sS -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/MinsukJi-NOAA/check-uptodate/issues/2/comments \
        -d '{"body": "'"${comment_body}"'"}'
