name: Pull request test

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  test1:
    name: test 1
    runs-on: ubuntu-20.04

    steps:
    - name: checkout codes
      uses: actions/checkout@v2

    - name: yes
      run: |
        sleep 60
        ./say-hello
